data:
  # specify the relative path of your data files
  path: "./data"

responsibility:
  text: "Transformation from ALTO4 to TEI by"
  # create a dictionary for each contributor in your project, featuring
  # their first name (forename), last name (surname), and ORCID (ptr)
  resp: [{"forename":"Sébastien", 
          "surname":"Biay",
          "ptr":{"type":"orcid","target":"000000027236874X"}
          },

        {"forename":"Mareike",
        "surname":"König",
         "ptr":{"type":"orcid","target":"000000027236874X"}
        },

        {"forename":"Anne",
        "surname":"Baillot",
         "ptr":{"type":"orcid","target":"000000027236874X"}
        }
        ]

  # name the publisher of this digital edition (project name)
  publisher: "Deutsches historisches Institut Paris"
  # name which authority finances or supports the project
  authority: ""
  # specify the edition's availability to the public/licencing
  availability: {"status": "restricted", "n":"CC BY-NC-ND 4.0"}
  licence: {"target":"https://creativecommons.org/licenses/by-nc-nd/4.0/"}
