data:
  # chemin relatif du dossier de données
  path: "./data"

responsibility:
  # nom de la personne responsable de l'encodage
  principal:
    forename: Sébastien
    surname: Biay
  # titre du projet
  title: La correspondance de Constance de Salm (1767-1845)
  # personnes responsables
  resp:
    [ { "forename": "Anne",
        "surname": "Baillot",
        },

      { "forename": "Mareike",
        "surname": "König",
      },
      { "forename": "Floriane",
        "surname": "Chiffoleau",
        }
    ]

  # Institution du projet éditorial
  publisher: "Deutsches historisches Institut Paris"
  # name which authority finances or supports the project
  authority: ""
  # specify the edition's availability to the public/licencing
  availability: {"status": "restricted", "n":"CC BY-NC-ND 4.0"}
  licence: {"target":"https://creativecommons.org/licenses/by-nc-nd/4.0/"}
